name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      versions:
        description: 'Comma-separated documentation versions to deploy (e.g. "10.0.x,10.1.x")'
        required: false
        default: '10.0.x'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.convert.outputs.versions }}
    steps:
      - name: Convert versions input to JSON array
        id: convert
        shell: bash
        run: |
          # If the input is empty (e.g., when triggered by push or PR), use the default value.
          if [ -z "${{ github.event.inputs.versions }}" ]; then
            versions="10.0.x"
          else
            versions="${{ github.event.inputs.versions }}"
          fi
          echo "Versions input: $versions"
          # Convert the comma-separated list to a JSON array.
          json_array=$(printf '["%s"]' "$(echo "$versions" | sed 's/,/","/g')")
          echo "JSON array: $json_array"
          echo "versions=$json_array" >> $GITHUB_OUTPUT

  build-docs:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare-matrix.outputs.versions) }}
    steps:
      - name: Echo
        shell: bash
        run: |
          echo ${{ matrix.version }}
