name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10.0.x, 10.1.x]
    steps:
      - name: Echo
        shell: bash
        run: |
          echo ${{ matrix.version }}
